"""add interaction follow up actions

Revision ID: a209b65bd9b5
Revises: bf112bd8988f
Create Date: 2026-07-13 21:37:38.591824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a209b65bd9b5'
down_revision: Union[str, Sequence[str], None] = 'bf112bd8988f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions",
        sa.Column(
            "follow_up_actions",
            sa.Text(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("interactions", "follow_up_actions", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'follow_up_actions')
    # ### end Alembic commands ###
